### ISSUE TITLE
404 on etf-public-dev repo

### ISSUE THREAD

**Issue by RomainWieser** [interactive-instruments/etf-webapp-docker#4]
Hi,

Using development branch, I get a 404 not found when docker-entrypoint.sh want to download latest version on https://services.interactive-instruments.de/etfdev-af/etf-public-dev.

This URL is set on file https://github.com/interactive-instruments/etf-webapp-docker/blob/dev/etfenv/etfwebapp.env. 

I don't think this is a normal behaviour ;)

**Comment by jonherrmann** [comment]
Hi Romain,

basically, it is not necessary to edit this file as the container will use the default settings from here:
https://github.com/interactive-instruments/etf-webapp-docker/blob/master/Dockerfile#L29-L32

I have added a note in the file.

It should work if you comment out the lines again, otherwise can you please add the full URL to the file which is tried to be downloaded, because directory listing on https://services.interactive-instruments.de/etfdev-af/etf-public-dev is switched off?

Please note that there is currently an issue so that the development version will fail to initialize #5 ... -we are working on it.
